// Bilingual Acceptance Criteria template.
// 0.1.0 required sections (PR #4 minimum): Acceptance Rules, Given When
//   Then, Failure Conditions.
// SOP 0.2.0 (DEC-023, additive only) requires a strictly different set:
//   Acceptance Items, Evidence Method, Pass Criteria, Failure Criteria,
//   Human Review Requirement. We keep both vocabularies in the same template
//   so neither runtime needs a separate file.

export const acceptanceCriteriaTemplate = `# Acceptance Criteria｜验收标准

> Generated by \`ocn doc create acceptance-criteria\`.
> Required sections (PR #4 minimum): Acceptance Rules, Given When Then, Failure Conditions.
> SOP 0.2.0 also requires: Acceptance Items, Evidence Method, Pass Criteria, Failure Criteria, Human Review Requirement.

## Acceptance Rules｜验收规则

<!-- The rule list. Numbered, each rule independently testable. -->

## Given When Then｜给定条件 执行动作 预期结果

<!--
Multiple Given/When/Then blocks. Example:

- Given the user has a fresh project
- When they run \`ocn init\`
- Then state.json carries currentStateId=state_discovery
-->

## Failure Conditions｜失败条件

<!-- The signals that say "this is broken". Exit codes, error codes, paths. -->

## Acceptance Items｜验收项

<!-- The numbered acceptance items used by docs/15-acceptance-mapping.md. -->

## Evidence Method｜证据方法

<!-- Per-item, the evidence kind: test name, command + expected output, etc. -->

## Pass Criteria｜通过标准

<!-- The exact signal that lets a reviewer mark each item PASS. -->

## Failure Criteria｜失败标准

<!-- The exact signal that lets a reviewer mark each item FAIL. -->

## Human Review Requirement｜人工评审要求

<!-- Which items require a named human reviewer in addition to test signals. -->

## Readiness Declarations｜就绪声明

<!-- SOP 0.4.0 readiness block — declare the scenario IDs (pointers, R1).
     The engine traces each ID against COLLECTED test node names
     (commands.test_list, e.g. pytest --collect-only -q) — comment
     references never count (R2). Empty list = UNKNOWN, never pass. -->

\`\`\`ocn-readiness
artifact: artifact_acceptance
fields: {}
# 填法（取消注释并填真实场景 ID）:
# fields:
#   scenarios: ["AC-F01", "AC-F02"]   # 每个 ID 须出现在真实测试函数名中
\`\`\`
`;
