// Bilingual Acceptance Criteria template — required sections per PR #4 §5:
// Acceptance Rules, Given When Then, Failure Conditions.

export const acceptanceCriteriaTemplate = `# Acceptance Criteria｜验收标准

> Generated by \`ocn doc create acceptance-criteria\`.
> Required sections (PR #4 minimum): Acceptance Rules, Given When Then, Failure Conditions.

## Acceptance Rules｜验收规则

<!-- The rule list. Numbered, each rule independently testable. -->

## Given When Then｜给定条件 执行动作 预期结果

<!--
Multiple Given/When/Then blocks. Example:

- Given the user has a fresh project
- When they run \`ocn init\`
- Then state.json carries currentStateId=state_discovery
-->

## Failure Conditions｜失败条件

<!-- The signals that say "this is broken". Exit codes, error codes, paths. -->
`;
