// Bilingual Acceptance Mapping template — required sections per SOP 0.2.0
// data.ts (step_acceptance_mapping): Acceptance Criterion, Evidence, Status,
// Notes, Human Review.

export const acceptanceMappingTemplate = `# Acceptance Mapping｜验收映射

> Generated by \`ocn doc create acceptance-mapping\`. Each acceptance
> criterion from docs/03-acceptance-criteria.md mapped to evidence and a
> human reviewer. Required sections (SOP 0.2.0): Acceptance Criterion,
> Evidence, Status, Notes, Human Review.

## Acceptance Criterion｜验收标准

<!-- The specific AC id / wording from docs/03-acceptance-criteria.md. -->

## Evidence｜证据

<!-- The artifact / test / log / screenshot that proves the criterion holds. -->

## Status｜状态

<!-- pass / fail / waived. Waived items must justify themselves in Notes. -->

## Notes｜说明

<!-- Context, caveats, follow-ups. Keep it auditable, not aspirational. -->

## Human Review｜人工评审

<!-- Reviewer identity + date. AI-generated mappings require human sign-off. -->
`;
