// Bilingual API Contract template — required sections per SOP 0.2.0 data.ts
// (step_api_contract): Endpoints, Request Schema, Response Schema, Error
// Shape, Authentication or Authorization, Compatibility Notes.
//
// 0.1.0 has step_api_contract as artifact-only with no required sections;
// this template is additive — adopting 0.2.0 sections costs the 0.1.0
// runtime nothing because the 0.1.0 gate ignores the extra headings.

export const apiContractTemplate = `# API Contract｜接口契约

> Generated by \`ocn doc create api-contract\`. Required sections (SOP
> 0.2.0): Endpoints, Request Schema, Response Schema, Error Shape,
> Authentication or Authorization, Compatibility Notes.

## Endpoints｜接口

<!-- Public surface. Method + path + 1-line purpose per endpoint. -->

## Request Schema｜请求结构

<!-- Per-endpoint request payload shape. Use Zod / JSON Schema if helpful. -->

## Response Schema｜响应结构

<!-- Per-endpoint success response shape. Pin field names and types. -->

## Error Shape｜错误结构

<!-- The unified error envelope. Error codes, HTTP statuses, message keys. -->

## Authentication or Authorization｜认证或授权

<!-- Auth scheme per endpoint. Roles, scopes, anonymous-allowed surfaces. -->

## Compatibility Notes｜兼容性说明

<!-- Backwards-compatibility commitments, versioning strategy, deprecations. -->
`;
