// Bilingual Build Plan template — required sections per SOP 0.2.0 data.ts
// (step_build_plan): Target Scope, Files Expected to Change, Implementation
// Tasks, Non-goals, Risk Points, Verification Commands. SOP 0.5.0
// (AM-007/DEC-032) adds the machine-parsed Task Specs section: the gate
// validates the task blocks and freezes their verify commands into
// .ocoding/task-ledger.json.

export const buildPlanTemplate = `# Build Plan｜构建计划

> Generated by \`ocn doc create build-plan\`. Lock the build target before
> implementation. Required sections (SOP 0.2.0): Target Scope, Files Expected
> to Change, Implementation Tasks, Non-goals, Risk Points, Verification
> Commands. SOP 0.5.0 additionally requires Task Specs｜任务规格.

## Target Scope｜目标范围

<!-- The build target for this iteration. What ships, scoped narrowly. -->

## Files Expected to Change｜预期变更文件

<!-- Concrete file paths (or globs) that this build expects to touch. -->

## Implementation Tasks｜实施任务

<!-- Ordered, atomic tasks. Each item should map to a single PR or commit. -->

## Non-goals｜非目标

<!-- Out-of-scope items for this build. Name them so they cannot creep back. -->

## Risk Points｜风险点

<!-- The places this plan can go wrong. Note mitigation per item. -->

## Verification Commands｜验证命令

<!-- The exact commands a reviewer must run to confirm the build is good. -->

## Task Specs｜任务规格

<!--
SOP 0.5.0 (AM-007 / DEC-032) — machine-parsed task spec blocks. The build-plan
gate validates them (six hard defects) and freezes each verify command into
.ocoding/task-ledger.json; \`ocn task check\` is then the ONLY way a task
becomes done. Write REAL tasks below this comment — the gate intentionally
blocks while this section has zero task blocks (an unsplit implementation is
not a plan).

Block format (one block per task):

### task_<slug>
- goal: what this task ships（一句话目标）
- traces: AC-001, AC-002        ← required; must resolve to real AC ids in docs/03
- touches: score_risk           ← optional; logic-graph node ids (.ocoding/logic-graph.json)
- verify: npm test -- --run x   ← required; deterministic shell command, frozen at gate pass
- dod: definition of done（给人读的完成定义）
- depends: task_other_id        ← optional; defined task ids, acyclic
- phase: P0                     ← optional; display/grouping only
- timeout: 120                  ← optional; verify timeout seconds (1-600, default 120)

拆分准则：一个任务 = 一次 PR 级增量（≤500 行 diff），自带独立、确定性的
verify 命令。Lists split on "," or "、". 勾销只能由验收命令裁定——没有人工
免跑通道；要砍任务就修订本节并重过门禁（已 done 且 verify 未变的任务保留状态）。
-->
`;
