// Bilingual Build Plan template — required sections per SOP 0.2.0 data.ts
// (step_build_plan): Target Scope, Files Expected to Change, Implementation
// Tasks, Non-goals, Risk Points, Verification Commands.

export const buildPlanTemplate = `# Build Plan｜构建计划

> Generated by \`ocn doc create build-plan\`. Lock the build target before
> implementation. Required sections (SOP 0.2.0): Target Scope, Files Expected
> to Change, Implementation Tasks, Non-goals, Risk Points, Verification
> Commands.

## Target Scope｜目标范围

<!-- The build target for this iteration. What ships, scoped narrowly. -->

## Files Expected to Change｜预期变更文件

<!-- Concrete file paths (or globs) that this build expects to touch. -->

## Implementation Tasks｜实施任务

<!-- Ordered, atomic tasks. Each item should map to a single PR or commit. -->

## Non-goals｜非目标

<!-- Out-of-scope items for this build. Name them so they cannot creep back. -->

## Risk Points｜风险点

<!-- The places this plan can go wrong. Note mitigation per item. -->

## Verification Commands｜验证命令

<!-- The exact commands a reviewer must run to confirm the build is good. -->
`;
