// Bilingual Change Evidence template — required sections per SOP 0.2.0
// data.ts (step_change_evidence): Git Diff Summary, Files Added, Files
// Modified, Files Deleted, Migration or Config Impact, Evidence Links or
// Commands.

export const changeEvidenceTemplate = `# Change Evidence｜变更证据

> Generated by \`ocn doc create change-evidence\`. The receipts for the build.
> Required sections (SOP 0.2.0): Git Diff Summary, Files Added, Files
> Modified, Files Deleted, Migration or Config Impact, Evidence Links or
> Commands.

## Git Diff Summary｜Git 差异摘要

<!-- High-level numstat or shortstat. Branch / base / commit pins live here. -->

## Files Added｜新增文件

<!-- New files this change introduces. Path + 1-line purpose. -->

## Files Modified｜修改文件

<!-- Files updated in place. Note semantic, not byte-level, changes. -->

## Files Deleted｜删除文件

<!-- Files removed. Confirm the removal does not break a documented contract. -->

## Migration or Config Impact｜迁移或配置影响

<!-- Schema migrations, config keys, env vars, deployment knobs touched. -->

## Evidence Links or Commands｜证据链接或命令

<!-- The reproducible commands or PR / commit URLs a reviewer can follow. -->
`;
