// Bilingual Data Model template — required sections per SOP 0.2.0 data.ts
// (step_data_model): Entities, Fields, Relationships, Constraints, Indexes
// or Access Patterns, Migration Notes.
//
// 0.1.0 has step_data_model as artifact-only with no required sections; this
// template is additive — adopting 0.2.0 sections costs the 0.1.0 runtime
// nothing because the 0.1.0 gate ignores the extra headings.

export const dataModelTemplate = `# Data Model｜数据模型

> Generated by \`ocn doc create data-model\`. Required sections (SOP 0.2.0):
> Entities, Fields, Relationships, Constraints, Indexes or Access Patterns,
> Migration Notes.

## Entities｜实体

<!-- Each domain entity. One paragraph per entity describing its purpose. -->

## Fields｜字段

<!-- Per-entity field tables: name, type, required, default, description. -->

## Relationships｜关系

<!-- Foreign-key / reference / containment relationships between entities. -->

## Constraints｜约束

<!-- Uniqueness, validation, business invariants the data layer enforces. -->

## Indexes or Access Patterns｜索引或访问模式

<!-- Read / write hot paths and the indexes (or query plans) they require. -->

## Migration Notes｜迁移说明

<!-- Forward-compatibility, backfill scripts, schema-version increments. -->
`;
