// Bilingual Failure Fix Log template — required sections per SOP 0.2.0
// data.ts (step_failure_fix_log): Failed Item, Root Cause, Fix Applied,
// Re-test Result, Remaining Risk.

export const failureFixLogTemplate = `# Failure Fix Log｜失败修复日志

> Generated by \`ocn doc create failure-fix-log\`. One entry per failure
> caught during verification. Required sections (SOP 0.2.0): Failed Item,
> Root Cause, Fix Applied, Re-test Result, Remaining Risk.

## Failed Item｜失败项

<!-- The acceptance item / test / smoke step that failed. Be specific. -->

## Root Cause｜根因

<!-- The actual cause, not the symptom. "Looks like X" is not a root cause. -->

## Fix Applied｜修复方案

<!-- The change that addresses the root cause. Link to commit / PR. -->

## Re-test Result｜回归结果

<!-- The exact command + result that proves the failure is gone. -->

## Remaining Risk｜剩余风险

<!-- What could still go wrong even after this fix. None is a valid answer. -->
`;
