// Bilingual Final Build Verdict template — required sections per SOP 0.2.0
// data.ts (step_final_build_verdict): Summary, Acceptance Status,
// Verification Status, Remaining Risks, Release Recommendation, Human
// Decision.

export const finalBuildVerdictTemplate = `# Final Build Verdict｜最终构建结论

> Generated by \`ocn doc create final-build-verdict\`. The single document a
> release reviewer reads to say yes / no. Required sections (SOP 0.2.0):
> Summary, Acceptance Status, Verification Status, Remaining Risks, Release
> Recommendation, Human Decision.

## Summary｜摘要

<!-- 3-5 sentences. What was built, against what plan, with what outcome. -->

## Acceptance Status｜验收状态

<!-- Roll-up of docs/15-acceptance-mapping.md: pass / fail / waived counts. -->

## Verification Status｜验证状态

<!-- Roll-up of docs/14-verification-report.md: lint / typecheck / test / build. -->

## Remaining Risks｜剩余风险

<!-- Open risks the release would carry. Tie each one to a follow-up. -->

## Release Recommendation｜发布建议

<!-- ship / hold / rework. Justify the recommendation with the data above. -->

## Human Decision｜人工决策

<!-- The named human who signed off, the date, and the recorded decision. -->
`;
