// Bilingual Implementation Log template — required sections per SOP 0.2.0
// data.ts (step_implementation_log): Files Changed, Change Summary, Commands
// Run, Deviations from Plan, Open Issues.

export const implementationLogTemplate = `# Implementation Log｜实现日志

> Generated by \`ocn doc create implementation-log\`. A factual record of what
> was actually built — not aspirational. Required sections (SOP 0.2.0): Files
> Changed, Change Summary, Commands Run, Deviations from Plan, Open Issues.

## Files Changed｜已变更文件

<!-- Every file actually touched. Group by area if the list is long. -->

## Change Summary｜变更摘要

<!-- A 3-7 bullet summary of behaviour-level changes — not file-level. -->

## Commands Run｜执行命令

<!-- The shell commands and their outcomes. Lint, typecheck, test, build. -->

## Deviations from Plan｜与计划的偏差

<!-- Where this implementation diverged from docs/10-build-plan.md and why. -->

## Open Issues｜遗留问题

<!-- Items knowingly left for a follow-up. Each should reference an owner. -->
`;
