// Bilingual Information Architecture template — required sections per SOP
// 0.2.0 data.ts (step_information_architecture): Navigation Structure, Page
// or Module Map, Object Hierarchy, User Entry Points, State and Permission
// Notes.
//
// 0.1.0 has step_information_architecture as artifact-only with no required
// sections; this template is additive — adopting 0.2.0 sections costs the
// 0.1.0 runtime nothing because the 0.1.0 gate ignores the extra headings.

export const informationArchitectureTemplate = `# Information Architecture｜信息架构

> Generated by \`ocn doc create information-architecture\`. Required
> sections (SOP 0.2.0): Navigation Structure, Page or Module Map, Object
> Hierarchy, User Entry Points, State and Permission Notes.

## Navigation Structure｜导航结构

<!-- Top-level navigation. Tabs, sidebars, breadcrumbs, command surfaces. -->

## Page or Module Map｜页面或模块地图

<!-- The list of pages / modules / commands and their parent-child links. -->

## Object Hierarchy｜对象层级

<!-- Domain object tree. Parent-child relationships and ownership rules. -->

## User Entry Points｜用户入口

<!-- How users land on each surface — deep links, search, share, CLI args. -->

## State and Permission Notes｜状态与权限说明

<!-- Auth gates, role-specific surfaces, empty-state handling per object. -->
`;
