// Bilingual Integration Notes template — required sections per SOP 0.2.0
// data.ts (step_integration_notes): Integration Points, Data Flow Impact,
// API Impact, UI Impact, Environment Impact, Rollback Notes.

export const integrationNotesTemplate = `# Integration Notes｜集成说明

> Generated by \`ocn doc create integration-notes\`. Surface every seam this
> change touches. Required sections (SOP 0.2.0): Integration Points, Data
> Flow Impact, API Impact, UI Impact, Environment Impact, Rollback Notes.

## Integration Points｜集成点

<!-- The systems / modules / contracts this change wires into. -->

## Data Flow Impact｜数据流影响

<!-- Producer / consumer changes; new or changed pipelines, queues, jobs. -->

## API Impact｜API 影响

<!-- Public surface — added, changed, removed endpoints; compatibility notes. -->

## UI Impact｜UI 影响

<!-- Routes, components, copy, accessibility deltas. None is a valid answer. -->

## Environment Impact｜环境影响

<!-- New env vars, infra dependencies, version bumps, capacity needs. -->

## Rollback Notes｜回滚说明

<!-- The exact steps to undo this change safely if production goes red. -->
`;
