// Bilingual Logic Backbone template — required sections per SOP 0.3.0
// data.ts (step_logic_backbone): Nodes, Dependencies, Decision Bindings,
// Signals, Graph. The Graph section carries the machine source of truth in an
// `ocn-logic-graph` fenced block; `ocn check` parses and validates it for the
// five drift defects (missing role, dangling reference, cycle, orphan,
// unbound trigger). Replace the example graph with your system's real one.

export const logicBackboneTemplate = `# Logic Backbone｜逻辑主干

> Generated by \`ocn doc create logic-backbone\`. This artifact pins the
> system's computation/decision graph BEFORE build so implementation cannot
> drift. Nodes carry a kind (input/formula/score/judgment/signal) and a role
> (input/intermediate/terminal_explanatory/trigger/hint). Edges are upstream→
> downstream: feeds / serves / triggers / explains.

## Nodes｜节点

<!-- Inventory every metric/formula/score/judgment/signal with its role.
     input · intermediate · terminal_explanatory · trigger · hint -->

| id | kind | role | label |
|---|---|---|---|
| input_raw | input | input | raw input |
| formula_norm | formula | intermediate | normalize |
| score_risk | score | intermediate | risk score |
| judgment_block | judgment | terminal_explanatory | block decision |
| signal_alert | signal | trigger | alert |

## Dependencies｜依赖

<!-- Execution order: what feeds what (defines the DAG). -->

- input_raw → formula_norm (feeds)
- formula_norm → score_risk (feeds)
- score_risk → signal_alert (feeds)

## Decision Bindings｜判断绑定

<!-- Which formula/score serves which judgment (DMN decision layering). -->

- formula_norm → judgment_block (serves)

## Signals｜信号

<!-- trigger = drives a function/action (must bind a triggers edge);
     hint = advisory only. -->

- signal_alert → judgment_block (triggers)

## Graph｜逻辑图

<!-- Machine source of truth. \`ocn check\` validates this block. -->

\`\`\`ocn-logic-graph
nodes:
  - id: input_raw
    kind: input
    role: input
    label: raw input
  - id: formula_norm
    kind: formula
    role: intermediate
    label: normalize
  - id: score_risk
    kind: score
    role: intermediate
    label: risk score
  - id: judgment_block
    kind: judgment
    role: terminal_explanatory
    label: block decision
  - id: signal_alert
    kind: signal
    role: trigger
    label: alert
edges:
  - from: input_raw
    to: formula_norm
    kind: feeds
  - from: formula_norm
    to: score_risk
    kind: feeds
  - from: formula_norm
    to: judgment_block
    kind: serves
  - from: score_risk
    to: signal_alert
    kind: feeds
  - from: signal_alert
    to: judgment_block
    kind: triggers
\`\`\`
`;
