// Bilingual MVP Plan template — required sections per SOP 0.2.0 data.ts
// (step_mvp_plan): Milestones, Task Breakdown, Build Order, Verification
// Plan, Cutline, Known Risks.
//
// 0.1.0 has step_mvp_plan as artifact-only with no required sections; this
// template is additive — adopting 0.2.0 sections costs the 0.1.0 runtime
// nothing because the 0.1.0 gate ignores the extra headings.

export const mvpPlanTemplate = `# MVP Plan｜MVP 计划

> Generated by \`ocn doc create mvp-plan\`. Required sections (SOP 0.2.0):
> Milestones, Task Breakdown, Build Order, Verification Plan, Cutline,
> Known Risks.

## Milestones｜里程碑

<!-- The headline milestones with target dates / signals. -->

## Task Breakdown｜任务分解

<!-- Atomic tasks per milestone. Owner + size + dependency notes. -->

## Build Order｜构建顺序

<!-- The ordered sequence to ship safely. Skeleton spike first if relevant. -->

## Verification Plan｜验证计划

<!-- How each milestone is verified — tests, demos, smoke runs, sign-offs. -->

## Cutline｜切线

<!-- The "must-have" / "should-have" cutline. What gets dropped if behind. -->

## Known Risks｜已知风险

<!-- Risks that could derail the plan and the planned mitigations. -->
`;
