// Bilingual PRD template.
// 0.1.0 required sections (Skeleton Spike): Problem, Goals, Users,
//   Scenarios, Requirements.
// SOP 0.2.0 (DEC-023, additive only) requires: Product Form, User Roles,
//   User Flow, Core Features, Non-functional Requirements (already present),
//   Acceptance Preconditions, Non-goals (already present). Adding the extras
//   keeps a single template compatible with both runtimes.

export const prdTemplate = `# Product Requirements Document｜产品需求文档

> Generated by \`ocn doc create prd\`. Replace placeholder text with real content.
> Skeleton Spike (0.1.0) required sections: Problem, Goals, Users, Scenarios, Requirements.
> SOP 0.2.0 also requires: Product Form, User Roles, User Flow, Core Features, Non-functional Requirements, Acceptance Preconditions, Non-goals.
> Run \`ocn check\` to verify the artifact gate.

## Problem｜问题

<!-- Describe the user/business problem this product solves. -->

## Goals｜目标

<!-- What success looks like for this release. -->

## Non-goals｜非目标

<!-- Explicit out-of-scope items. -->

## Users｜用户

<!-- Who is affected — primary, secondary. -->

## User Roles｜用户角色

<!-- Each distinct role and what they can do in this product. -->

## User Flow｜用户流程

<!-- The end-to-end flow per primary persona. Pre-conditions, steps, exits. -->

## Scenarios｜使用场景

<!-- 3-7 representative end-to-end scenarios. -->

## Product Form｜产品形态

<!-- The shipped form (CLI / web / library / MCP server / etc) and its surface. -->

## Core Features｜核心功能

<!-- The flagship capabilities of this release. Numbered, each linkable. -->

## Requirements｜需求

<!-- Functional and non-functional, with priority. -->

## Acceptance Preconditions｜验收前置条件

<!-- The conditions that must hold before acceptance testing can begin. -->

## Risks｜风险

<!-- Top risks and mitigation pointers. -->

## Business Rules｜业务规则

<!-- Domain rules, invariants. -->

## Permission Rules｜权限规则

<!-- Who can do what. -->

## Exception Scenarios｜异常场景

<!-- Failure modes and expected behaviour. -->

## Non-functional Requirements｜非功能性需求

<!-- Performance, reliability, security, observability. -->

## Step Artifact Gate Self-check｜步骤产物门禁自检

- [ ] Problem｜问题
- [ ] Goals｜目标
- [ ] Non-goals｜非目标
- [ ] Users｜用户
- [ ] Scenarios｜使用场景
- [ ] Requirements｜需求

## Readiness Declarations｜就绪声明

<!-- SOP 0.4.0 readiness block — machine source for this doc's readiness
     fields (inert on older profiles). R1: fill pointers/parameters only
     (numbers, IDs, thresholds, paths) — never conclusions; booleans are
     schema-illegal. Unfilled fields evaluate as UNKNOWN (silence is never
     pass). Uncomment the example lines under \`fields:\` with real values. -->

\`\`\`ocn-readiness
artifact: artifact_prd
fields: {}
# 填法（取消注释并填真实值）:
# fields:
#   requirements: 5                            # count_gte:1（结构化需求条数）
#   security_constraints: 2                    # count_gte:1（显式安全约束条数）
#   value_proposition: "为谁解决什么"           # not_empty
\`\`\`
`;
