// Bilingual Project Brief template.
// 0.1.0 required sections (PR #4 minimum): Problem, Goal, Users, Success
//   Criteria.
// SOP 0.2.0 (DEC-023, additive only — see 0.2.0/data.ts) adds: Constraints,
//   Risks, Non-goals. Adding the extra headings here keeps a single template
//   compatible with both runtimes — the 0.1.0 gate ignores the extras and
//   the 0.2.0 gate (wired in PR 3) finds them present.

export const projectBriefTemplate = `# Project Brief｜项目简报

> Generated by \`ocn doc create project-brief\`. Replace placeholder text with real content.
> Required sections (PR #4 minimum): Problem, Goal, Users, Success Criteria.
> SOP 0.2.0 also requires: Constraints, Risks, Non-goals (additive).
> Run \`ocn check\` or \`ocn gate\` to verify the artifact gate.

## Problem｜问题

<!-- What user/business problem does this project solve? Be concrete. -->

## Goal｜目标

<!-- One-sentence north-star outcome. Singular by design. -->

## Users｜用户

<!-- Primary, secondary. What do they currently do without this product? -->

## Success Criteria｜成功标准

<!-- Measurable signals that say "we won". 2-5 items, each verifiable. -->

## Constraints｜约束

<!-- Hard constraints from environment, regulation, contract, or platform. -->

## Risks｜风险

<!-- Top risks that could derail the project, plus mitigation pointers. -->

## Non-goals｜非目标

<!-- Explicitly out-of-scope outcomes. Naming them prevents scope creep. -->

## Readiness Declarations｜就绪声明

<!-- SOP 0.4.0 readiness block — machine source for this doc's readiness
     fields (inert on older profiles). R1: fill pointers/parameters only
     (numbers, IDs, thresholds, paths) — never conclusions; booleans are
     schema-illegal. Unfilled fields evaluate as UNKNOWN (silence is never
     pass). Uncomment the example lines under \`fields:\` with real values. -->

\`\`\`ocn-readiness
artifact: artifact_brief
fields: {}
# 填法（取消注释并填真实值）:
# fields:
#   problem_statement: "一句话问题定义"        # not_empty
\`\`\`
`;
