// Bilingual Project Brief template — required sections per PR #4 plan §5:
// Problem, Goal (singular), Users, Success Criteria.

export const projectBriefTemplate = `# Project Brief｜项目简报

> Generated by \`ocn doc create project-brief\`. Replace placeholder text with real content.
> Required sections (PR #4 minimum): Problem, Goal, Users, Success Criteria.
> Run \`ocn check\` or \`ocn gate\` to verify the artifact gate.

## Problem｜问题

<!-- What user/business problem does this project solve? Be concrete. -->

## Goal｜目标

<!-- One-sentence north-star outcome. Singular by design. -->

## Users｜用户

<!-- Primary, secondary. What do they currently do without this product? -->

## Success Criteria｜成功标准

<!-- Measurable signals that say "we won". 2-5 items, each verifiable. -->
`;
