// Bilingual Regression Evidence template — required sections per SOP 0.2.0
// data.ts (step_regression_evidence): Regression Scope, Commands Run,
// Result, Previously Broken Behavior, Current Behavior, Residual Risk.

export const regressionEvidenceTemplate = `# Regression Evidence｜回归证据

> Generated by \`ocn doc create regression-evidence\`. The proof every fixed
> failure stays fixed. Required sections (SOP 0.2.0): Regression Scope,
> Commands Run, Result, Previously Broken Behavior, Current Behavior,
> Residual Risk.

## Regression Scope｜回归范围

<!-- Which areas were re-tested. Link to docs/16-failure-fix-log.md entries. -->

## Commands Run｜执行命令

<!-- The exact commands that produced the evidence below. Reproducible. -->

## Result｜结果

<!-- pass / fail summary, plus link to log output if available. -->

## Previously Broken Behavior｜此前异常行为

<!-- What the system did before the fix. Quote logs / screenshots if useful. -->

## Current Behavior｜当前行为

<!-- What the system does now. Demonstrate the contrast against the above. -->

## Residual Risk｜残留风险

<!-- Remaining gaps the regression run did not cover. Honest is required. -->
`;
