// Bilingual Scope template.
// 0.1.0 required sections (PR #4 minimum): In Scope, Out of Scope, Technical
//   Constraints, Completion Boundary.
// SOP 0.2.0 (DEC-023, additive only) adds: Exclusions, Assumptions. Adding
//   the extras keeps a single template compatible with both runtimes — the
//   0.1.0 gate ignores them and the 0.2.0 gate (PR 3) finds them present.

export const scopeTemplate = `# Scope｜范围

> Generated by \`ocn doc create scope\`. Lock the boundary before design.
> Required sections (PR #4 minimum): In Scope, Out of Scope, Technical Constraints, Completion Boundary.
> SOP 0.2.0 also requires: Exclusions, Assumptions (additive).

## In Scope｜范围内

<!-- The features, surfaces, and outcomes that this version commits to. -->

## Out of Scope｜范围外

<!-- Explicitly excluded items — name them so they cannot creep back. -->

## Technical Constraints｜技术约束

<!-- Hard constraints from environment, regulation, or platform decisions. -->

## Completion Boundary｜完成边界

<!-- The "we are done" line. What artifact / metric / behavior signals it? -->

## Exclusions｜排除项

<!-- Categorical exclusions: not just features but entire user segments,
     deployment targets, or integration channels we will not support. -->

## Assumptions｜假设

<!-- The assumptions this scope rests on. Each one becomes a risk if it
     turns out false; track them so verification can challenge them. -->
`;
