// Bilingual Scope template.
// 0.1.0 required sections (PR #4 minimum): In Scope, Out of Scope, Technical
//   Constraints, Completion Boundary.
// SOP 0.2.0 (DEC-023, additive only) adds: Exclusions, Assumptions. Adding
//   the extras keeps a single template compatible with both runtimes — the
//   0.1.0 gate ignores them and the 0.2.0 gate (PR 3) finds them present.

export const scopeTemplate = `# Scope｜范围

> Generated by \`ocn doc create scope\`. Lock the boundary before design.
> Required sections (PR #4 minimum): In Scope, Out of Scope, Technical Constraints, Completion Boundary.
> SOP 0.2.0 also requires: Exclusions, Assumptions (additive).

## In Scope｜范围内

<!-- The features, surfaces, and outcomes that this version commits to. -->

## Out of Scope｜范围外

<!-- Explicitly excluded items — name them so they cannot creep back. -->

## Technical Constraints｜技术约束

<!-- Hard constraints from environment, regulation, or platform decisions. -->

## Completion Boundary｜完成边界

<!-- The "we are done" line. What artifact / metric / behavior signals it? -->

## Exclusions｜排除项

<!-- Categorical exclusions: not just features but entire user segments,
     deployment targets, or integration channels we will not support. -->

## Assumptions｜假设

<!-- The assumptions this scope rests on. Each one becomes a risk if it
     turns out false; track them so verification can challenge them. -->

## Readiness Declarations｜就绪声明

<!-- SOP 0.4.0 readiness block — machine source for this doc's readiness
     fields (inert on older profiles). R1: fill pointers/parameters only
     (numbers, IDs, thresholds, paths) — never conclusions; booleans are
     schema-illegal. Unfilled fields evaluate as UNKNOWN (silence is never
     pass). Uncomment the example lines under \`fields:\` with real values. -->

\`\`\`ocn-readiness
artifact: artifact_scope
fields: {}
# 填法（取消注释并填真实值）:
# fields:
#   stop_conditions: ["GA = 通过率 ≥95%"]      # count_gte:1（可量化）
#   in_scope: "核心 Runtime / 门禁 / …"        # not_empty
#   must_not_do: "永久不做清单见上文"          # not_empty
#   mobile_target: "N/A 非移动项目"            # not_empty（或走 WAIVED）
\`\`\`
`;
