// Bilingual Technical Architecture template.
// 0.1.0 required sections (PR #4 minimum): Product Form, Runtime, Language,
//   Storage, Final Decision.
// SOP 0.2.0 (DEC-023, additive only) requires: Product Form, Runtime,
//   Language, Frameworks, Storage, Integration, Deployment Form, Non-goals,
//   Decision Matrix, Constraints, Risks, Final Decision. Adding the extras
//   keeps a single template compatible with both runtimes.

export const technicalArchitectureTemplate = `# Technical Architecture｜技术架构

> Generated by \`ocn doc create technical-architecture\`. Lock structural choices before deeper design.
> Required sections (PR #4 minimum): Product Form, Runtime, Language, Storage, Final Decision.
> SOP 0.2.0 also requires: Frameworks, Integration, Deployment Form, Non-goals, Decision Matrix, Constraints, Risks (additive).

## Product Form｜产品形态

<!-- CLI? Library? Service? MCP server? Pick one and own it. -->

## Runtime｜运行时

<!-- Node version, browser support, target platform. -->

## Language｜开发语言

<!-- TypeScript? Rust? Multi-language? Reason here, not later. -->

## Frameworks｜框架

<!-- Web framework, CLI framework, MCP SDK, etc. Choose explicitly. -->

## Storage｜存储方案

<!-- Filesystem? SQLite? Postgres? When does each kick in? -->

## Integration｜集成

<!-- Upstream / downstream systems, queues, scheduling, observability stack. -->

## Deployment Form｜部署形态

<!-- npm package? docker image? lambda? Long-running service? Hybrid? -->

## Non-goals｜非目标

<!-- Architectural directions deliberately not pursued in this iteration. -->

## Decision Matrix｜决策矩阵

<!-- The trade-off table that produced the choices above (option vs criteria). -->

## Constraints｜约束

<!-- Hard architectural constraints from environment, regulation, contract. -->

## Risks｜风险

<!-- Architectural risks and mitigations. -->

## Final Decision｜最终决策

<!-- One-paragraph summary that answers: when someone asks "what is it built on?",
     what do you tell them in 30 seconds? -->
`;
