// Bilingual Technical Architecture template — required sections per PR #4 §5:
// Product Form, Runtime, Language, Storage, Final Decision.

export const technicalArchitectureTemplate = `# Technical Architecture｜技术架构

> Generated by \`ocn doc create technical-architecture\`. Lock structural choices before deeper design.
> Required sections (PR #4 minimum): Product Form, Runtime, Language, Storage, Final Decision.

## Product Form｜产品形态

<!-- CLI? Library? Service? MCP server? Pick one and own it. -->

## Runtime｜运行时

<!-- Node version, browser support, target platform. -->

## Language｜开发语言

<!-- TypeScript? Rust? Multi-language? Reason here, not later. -->

## Storage｜存储方案

<!-- Filesystem? SQLite? Postgres? When does each kick in? -->

## Final Decision｜最终决策

<!-- One-paragraph summary that answers: when someone asks "what is it built on?",
     what do you tell them in 30 seconds? -->
`;
