// Bilingual Test Strategy template — required sections per SOP 0.2.0
// data.ts (step_test_strategy): Unit Tests, Integration Tests, E2E or Smoke
// Tests, Fixtures, Coverage Expectation, Non-testable Risks.
//
// 0.1.0 has step_test_strategy as artifact-only with no required sections;
// this template is additive — adopting 0.2.0 sections costs the 0.1.0
// runtime nothing because the 0.1.0 gate ignores the extra headings.

export const testStrategyTemplate = `# Test Strategy｜测试策略

> Generated by \`ocn doc create test-strategy\`. Required sections (SOP
> 0.2.0): Unit Tests, Integration Tests, E2E or Smoke Tests, Fixtures,
> Coverage Expectation, Non-testable Risks.

## Unit Tests｜单元测试

<!-- The pure-function / module-level unit-test surface and ownership. -->

## Integration Tests｜集成测试

<!-- Cross-module or cross-service boundary tests. Where they live. -->

## E2E or Smoke Tests｜端到端或冒烟测试

<!-- The shortlist of end-user flows whose green run blocks release. -->

## Fixtures｜测试夹具

<!-- Shared fixtures, factories, seed data. Generation rules. -->

## Coverage Expectation｜覆盖率期望

<!-- Per-layer minimum coverage and the rationale for each threshold. -->

## Non-testable Risks｜不可测试风险

<!-- Risks the test suite cannot catch — escalate to manual review. -->

## Readiness Declarations｜就绪声明

<!-- SOP 0.4.0 readiness block — machine source for this doc's readiness
     fields (inert on older profiles). R1: fill pointers/parameters only
     (numbers, IDs, thresholds, paths) — never conclusions; booleans are
     schema-illegal. Unfilled fields evaluate as UNKNOWN (silence is never
     pass). Uncomment the example lines under \`fields:\` with real values. -->

\`\`\`ocn-readiness
artifact: artifact_test_strategy
fields: {}
# 填法（取消注释并填真实值）:
# fields:
#   coverage_target: "行覆盖 ≥80%"             # numeric_with_unit（拒绝 TBD）
\`\`\`
`;
