// Bilingual Verification Report template — required sections per SOP 0.2.0
// data.ts (step_verification_report): Lint Result, Typecheck Result, Test
// Result, Coverage Result, Build Result, Smoke Result, Known Failures.

export const verificationReportTemplate = `# Verification Report｜验证报告

> Generated by \`ocn doc create verification-report\`. The signed-off proof
> the build passes its quality gate. Required sections (SOP 0.2.0): Lint
> Result, Typecheck Result, Test Result, Coverage Result, Build Result,
> Smoke Result, Known Failures.

## Lint Result｜Lint 结果

<!-- Command + status (pass / fail) + warning count summary. -->

## Typecheck Result｜类型检查结果

<!-- \`tsc --noEmit\` or equivalent. Summary of any suppressed errors. -->

## Test Result｜测试结果

<!-- Total / passed / skipped. Link to the run if CI captured it. -->

## Coverage Result｜覆盖率结果

<!-- Statement / branch / function coverage vs the project minimum. -->

## Build Result｜构建结果

<!-- \`npm run build\` (or equivalent) status and artifact paths. -->

## Smoke Result｜冒烟测试结果

<!-- Manual or scripted smoke run on the built artifact. -->

## Known Failures｜已知失败

<!-- Anything red that ships anyway. Each item must justify itself. -->
`;
